FROM alpine

RUN apk add dhcp

ARG CFG_FILE=/etc/dhcp/dhcpd.conf

RUN echo "authoritative;" > $CFG_FILE && \
    echo "subnet 172.17.0.0 netmask 255.255.255.0 {" >> $CFG_FILE && \
    echo "    option domain-name domain;" >> $CFG_FILE && \
    echo "    option domain-name-servers 192.168.1.1, 192.168.1.1;" >> $CFG_FILE && \
    echo "    option routers 172.17.0.1;" >> $CFG_FILE && \
    echo "    range 172.17.0.100 172.17.0.200;" >> $CFG_FILE && \
    echo "}" >> $CFG_FILE 

RUN touch /var/lib/dhcp/dhcpd.leases

CMD dhcpd -d    