FROM golang:1.14-alpine

RUN apk update && apk --no-cache upgrade && apk add --no-cache gcc musl-dev dep git upx ca-certificates tzdata busybox-static

ENV SRC /go/src/github.com/zauberhaus/rest2dhcp
ENV TZ=Pacific/Auckland

COPY . $SRC
WORKDIR $SRC

CMD OUT=/opt/rest2dhcp ./build.sh
