FROM golang:1.14-alpine

RUN apk update && apk --no-cache upgrade && apk add --no-cache gcc musl-dev dep git upx ca-certificates tzdata busybox-static

ENV SRC /go/src/github.com/zauberhaus/rest2dhcp
ENV TZ=Pacific/Auckland
ENV OUT=/out/rest2dhcp

COPY . $SRC
WORKDIR $SRC

CMD ./build.sh
