FROM golang:1.16-alpine

RUN apk update && apk --no-cache upgrade && apk add --no-cache git
RUN go get github.com/mjibson/esc

ENV SRC /go/src/github.com/zauberhaus/rest2dhcp
ENV CGO_ENABLED 0
ENV SERVER ""
ENV CLIENT ""
ENV RELAY ""
ENV MODE "auto"

COPY . $SRC
RUN cd $SRC && go mod download
WORKDIR $SRC

CMD cd $SRC && go generate ./service/server.go && go test -v ./...

