FROM alpine:3.15

RUN apk add dhcp

ENV CFG_FILE=/etc/dhcp/dhcpd.conf
ENV NAMESERVERS=
ENV ROUTER=
ENV DOMAIN=

RUN touch /var/lib/dhcp/dhcpd.leases
COPY ./entrypoint_dhcpd.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]    