version: "3"
services:
  dhcpd:
    image: dhcpd
    build: 
      context: .
      dockerfile: ./Dockerfile.dhcpd
    networks:
      - dhcp      

  dnsmasq:
    image: dnsmasq
    build: 
      context: .
      dockerfile: ./Dockerfile.dnsmasq
    cap_add:
      - NET_ADMIN      
    networks:
      - dhcp      

  rest2dhcp:
    image: rest2dhcp
    build: 
      context: ..
      dockerfile: ./Dockerfile.alpine
    environment:
      - VERBOSE=true
      - DHCP_SERVER=dhcpd
      - BASE_URL=localhost:8080
      - MODE=udp
    ports:
      - 8080:8080
    links:
      - dhcpd
      - dnsmasq  
    depends_on:
      - dnsmasq        
      - dhcpd
    networks:
      - dhcp      
      
  test:
    image: rest2dhcp_test
    build: 
      context: .
      dockerfile: ./Dockerfile
    links:
      - rest2dhcp
    depends_on:
      - rest2dhcp        
    networks:
      - dhcp      

networks:
  dhcp:     
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
