client: 11.11.11.11
server: 22.22.22.22
relay: 33.33.33.33
mode: broken
timeout: 13m
dhcp-timeout: 27s
retry: 38000ms
quiet: true
verbose: true
access-log: false
listen: "hier:7625"
kubeconfig: abcdefg
namespace: ns001
service: svr001
