name: "SonarCloud"

on:
  push:
    branches: [ dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare 
      id: prepare
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}

    - name: Tests 
      run: |
        go install github.com/mjibson/esc@latest
        go generate ./service/server.go
        go test -coverprofile=coverage.out ./background ./client ./cmd ./dhcp ./kubernetes ./service
    - name: SonarCloud Scan
      if: success()
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectVersion=${{ steps.prepare.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
