name: Test master

on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.2
        with:
          go-version: ~1.14
        id: go      

      - name: Run tests
        run: ./scripts/test-local-dhcp.sh  
  
