# This is a basic workflow to help you get started with Actions

name: Tests

on:
  pull_request:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        goversion: ['1.16']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Tests 
      run: |
        go get github.com/mjibson/esc
        go get github.com/jandelgado/gcov2lcov
        go generate ./service/server.go
        go test -v -race -timeout=30s ./... 
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      if: success() && matrix.platform == 'ubuntu-latest'
      run: |
        gcov2lcov -infile coverage.out -outfile /tmp/coverage.lcov
    - name: Coveralls
      if: success() && matrix.platform == 'ubuntu-latest'
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: /tmp/coverage.lcov

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Tests 
      run: |
        go get github.com/mjibson/esc
        go get github.com/jandelgado/gcov2lcov
        go generate ./service/server.go
        go test -coverprofile=coverage.out ./background ./client ./cmd ./dhcp ./kubernetes ./service
    - name: SonarCloud Scan
      if: success()
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  integration-test:
    strategy:
      matrix:
        goversion: ['1.16']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Integration tests 
      run: |
        go install github.com/onsi/ginkgo/ginkgo
        cd tests && \
        ./run.sh
