# This is a basic workflow to help you get started with Actions

name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        goversion: ['1.16']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests 
      run: |
        go get github.com/mjibson/esc
        go get github.com/jandelgado/gcov2lcov
        go generate ./service/server.go
        go test -v -race -timeout=30s ./client ./dhcp ./cmd ./service ./background
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      if: success() && matrix.platform == 'ubuntu-latest'
      run: |
        gcov2lcov -infile coverage.out -outfile /tmp/coverage.lcov
    - name: Coveralls
      if: success() && matrix.platform == 'ubuntu-latest'
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: /tmp/coverage.lcov

