name: Test master

on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.2
        with:
          go-version: ~1.14
        id: go      

      - name: Start DHCP server
        id: dhcp
        run: |
          docker build -t dhcp -f Dockerfile.dhcp .
          DHCP_ID=`docker run -d --rm --name dhcp dhcp`  
          DHCP_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dhcp`
          echo ::set-output name=id::${DHCP_ID}
          echo ::set-output name=ip::${DHCP_IP}

      - name: Build test container
        run: docker build -t rest2dhcp:test -f Dockerfile.wf .  
  
      - name: Run udp tests
        run: docker run --rm -e SERVER=${{ steps.dhcp.outputs.ip }} -e MODE=udp rest2dhcp:test  
