name: "Unit Tests"

on:
  push:
    branches: [ dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  test:
    strategy:
      matrix:
        goversion: ['1.17']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Tests 
      run: |
        go install github.com/mjibson/esc@latest
        go install github.com/jandelgado/gcov2lcov@latest
        go generate ./service/server.go
        go test -v -race -timeout=30s ./... 
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      if: success() && matrix.platform == 'ubuntu-latest'
      run: |
        gcov2lcov -infile coverage.out -outfile /tmp/coverage.lcov
    - name: Coveralls
      if: success() && matrix.platform == 'ubuntu-latest'
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: /tmp/coverage.lcov

